name: Test Suite

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'

      - name: Install Dependencies
        working-directory: webapp
        run: npm ci

      - name: Run Tests
        working-directory: webapp
        run: npm run test
